apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/mariadb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  labels:
    app: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb
        env:
        - name: MYSQL_DATABASE
          value: wiki
        - name: MYSQL_USER
          value: wikiadmin
        - name: MYSQL_PASSWORD
          value: passwd
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: 'yes'
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-ps
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-ps
        persistentVolumeClaim:
          claimName: mariadb-pv-claim
      

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
spec:
  selector:
    app: mariadb
  ports:
  - port: 3306
  clusterIP: None
